CREATE TABLE IF NOT EXISTS DEPARTMENT (
    EMPLOYEE_ID TEXT,
    NAME TEXT,
    DEPARTMENT_ID TEXT,
    MANAGER_ID TEXT,
    SALARY REAL
);

INSERT INTO DEPARTMENT (EMPLOYEE_ID, NAME, DEPARTMENT_ID, MANAGER_ID, SALARY) VALUES
('100','STEVEN KING','90','101',240000),
('101','NEENA KUMAR','90','102',170000),
('102','LEX DE HOOFT','90','106',170000),
('103','DAI RICHARD','60','104',90000),
('104','SUSAN MURPHY','60','105',80000),
('105','HERMAN BAILEY','50','103',80000),
('1973','WILLIAM GATES','60','107',60000),
('107','JAMES BOND','90','104',50000);

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',
    COUNT(*) AS 'NUMBER OF EMPLOYEES'
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID,SUM(SALARY)
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',
    COUNT(*) AS 'NUMBER OF EMPLOYEES',
    SUM(SALARY) AS 'TOTAL SALARY'
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID AS 'DEPARTMENT CODE',
    SUM(SALARY) AS 'TOTAL SALARY'
FROM DEPARTMENT
WHERE MANAGER_ID='103'
GROUP BY DEPARTMENT_ID;

SELECT DEPARTMENT_ID,COUNT(*) AS 'NUMBER OF EMPLOYEES'
FROM DEPARTMENT
GROUP BY DEPARTMENT_ID
HAVING COUNT(*)>2;